[target.aarch64-unknown-linux-musl]
linker = "clang"
rustflags = [
    "-C", "link-arg=-fuse-ld=mold",
    "-C", "link-arg=--target=aarch64-unknown-linux-musl",
]

[target.x86_64-unknown-linux-musl]
linker = "clang"
rustflags = [
    "-C", "link-arg=-fuse-ld=mold",
    "-C", "link-arg=--target=x86_64-unknown-linux-musl",
]
