name: Build and Publish Docker Images

on:
  # on every published tag
  release:
    types: [ "published" ]
  # Run this workflow on every push to the 'main' branch
  # push:
  #   branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository code
      - name: Check out code
        uses: actions/checkout@v4

      # 2. Log in to Docker Hub
      # Uses secrets store in GitHub Settings
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. Build and push the image
      - name: Build and push lcov2xml Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./lcov2xml.Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/lcov2xml:${{ github.ref_name }}
            ${{ secrets.DOCKERHUB_USERNAME }}/lcov2xml:latest

      # 4. Build and push the image
      - name: Build and push cobertura_split Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./cobertura_split.Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/cobertura_split:${{ github.ref_name }}
            ${{ secrets.DOCKERHUB_USERNAME }}/cobertura_split:latest
